version: "3.8"

services:
  openfire:
    build:
      context: .
      dockerfile: Dockerfile_local
      args:
        - AWS_REGION=eu-central-1
    environment:
      - DB_USER=openfire
      - DB_PASS=testpass
      - DB_URL=host.docker.internal
      - DB_NAME=openfire
      - AWS_REGION=eu-central-1
      - SERVICE_NAME=stage-chat
      - CLUSTER_NAME=stage-ecs-cluster
      - SUBNET='10.0.*.*'
    ports:
      - "3478"
      - "3479"
      - "5222"
      - "5223"
      - "5229"
      - "5275"
      - "5276"
      - "5262"
      - "5263"
      - "5701"
      - "7070"
      - "7443"
      - "7777"
      - "9090"
      - "9091"
    networks:
      - inner
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - openfire
    ports:
      - "9090:9090"
    networks:
      - inner

volumes:
  db-data:

networks:
  inner:
