version: "3.8"

services:
  openfire-local:
    build:
      context: .
      dockerfile: Dockerfile_local
      args:
        - AWS_REGION=eu-central-1
    environment:
      - DB_USER=openfire
      - DB_PASS=testpass
      - DB_URL=host.docker.internal
      - DB_NAME=openfire
      - AWS_REGION=eu-central-1
      - SERVICE_NAME=stage-chat
      - CLUSTER_NAME=stage-ecs-cluster
      - SUBNET='10.0.*.*'
    ports:
      - "3478:3478"
      - "3479:3479"
      - "5222:5222"
      - "5223:5223"
      - "5229:5229"
      - "5275:5275"
      - "5276:5276"
      - "5262:5262"
      - "5263:5263"
      - "5701:5701"
      - "7070:7070"
      - "7443:7443"
      - "7777:7777"
      - "9090:9090"
      - "9091:9091"
      - "5005:5005"
    networks:
      - inner

networks:
  inner:
