version: "3.8"
services:
    openfire:
        build:
            context: .
            dockerfile: Dockerfile_local
            args:
                VERSION_DBACCESS: 1.2.2
                VERSION_REGISTRATION: 1.7.2
                VERSION_RESTAPI: 1.4.0
                VERSION_SUBSCRIPTION: 1.4.0
                DB_NAME: openfire
                DB_USER: openfire
                DB_PASS: /run/secrets/db_password
                DB_URL: localhost
                OPENFIRE_USER: openfire
                OPENFIRE_DIR: /usr/local/openfire
                OPENFIRE_DATA_DIR: /var/lib/openfire
                OPENFIRE_LOG_DIR: /var/log/openfire
        environment:
            OPENFIRE_USER: openfire
            OPENFIRE_DIR: /usr/local/openfire
            OPENFIRE_DATA_DIR: /var/lib/openfire
            OPENFIRE_LOG_DIR: /var/log/openfire
        depends_on:
            - db
        networks:
            - inner
        ports:
            - "3478"
            - "3479"
            - "5222"
            - "5223"
            - "5229"
            - "5275"
            - "5276"
            - "5262"
            - "5263"
            - "5701"
            - "7070"
            - "7443"
            - "7777"
            - "9090"
            - "9091"
        secrets:
            - db_password
            - ssh_private
            - aws
        volumes:
            - "of-data:${OPENFIRE_DATA_DIR}"

    db:
        image: mysql:latest
        networks:
            - inner
        volumes:
            - db-data:/var/lib/mysql/data
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_DATABASE: openfire
            MYSQL_USER: openfire
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_root_password
            - db_password

secrets:
    db_password:
        file: ./db_password.txt
    db_root_password:
        file: ./db_root_password.txt
    ssh_private:
        file: ~/.ssh/id_rsa
    aws:
        file: ~/.aws/credentials

volumes:
    db-data:
    of-data:

networks:
    inner:
