# Continuous Integration workflow
name: CI

# run all integration jobs on pull request
on:
  pull_request

jobs:
  # one job for building and testing
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # TODO check as first step if code formatting with .editorconfig is applied properly

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java${{ matrix.java }}-maven-
            ${{ runner.os }}-

      - name: Build with Maven
        run: mvn -B package -Pcoverage -Denv=test --file pom.xml
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: distribution-java${{ matrix.java }}
          path: distribution/target/distribution-base
      - name: Upload test files
        uses: actions/upload-artifact@v2
        with:
          name: test-files
          path: |
            runIntegrationTests
            runAioxmppIntegrationTests
            test.gradle

  aioxmpp:

    name: Execute aioxmpp-based CI tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download distribution artifact from build job.
        uses: actions/download-artifact@v2
        with:
          name: distribution-java11
          path: distribution/target/distribution-base
      - name: Download test files from build job.
        uses: actions/download-artifact@v2
        with:
          name: test-files
      - name: Fix file permissions
        run: |
          chmod +x distribution/target/distribution-base/bin/openfire.sh
          chmod +x ./runAioxmppIntegrationTests
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Run aioxmpp tests
        run: ./runAioxmppIntegrationTests -d -l -h example.org -i 127.0.0.1 || ./runAioxmppIntegrationTests -d -l -h example.org -i 127.0.0.1 || ./runAioxmppIntegrationTests -d -l -h example.org -i 127.0.0.1 # Try tests a few times, in case of flakiness

      - name: Expose test output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: aioxmpp test output
          path: aioxmpp/output
